# Generated by Django 5.0 on 2023-12-11 11:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Your first name', max_length=264)),
                ('last_name', models.CharField(default='Your last name', max_length=264)),
                ('email', models.EmailField(default='XXX@123.com', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='CA')),
                ('role', models.BooleanField(default=True)),
            ],
        ),
    ]
